@startuml

entity "channels" {
  + id : int
  --
  name : varchar
}

entity "shows" {
  + id : int
  --
  title : varchar
  description : varchar
}

entity "seasons" {
  + id : int
  --
  season_number : int
  show_id : int
}

entity "episodes" {
  + id : int
  --
  title : varchar
  description : varchar
  episode_number : int
  season_id : int
}

entity "time_slots" {
  + id : int
  --
  start_time : datetime
  end_time : datetime
  channel_id : int
}

entity "view_counts" {
  + id : int
  --
  views : int
  episode_id : int
  time_slot_id : int
}

entity "genres" {
  + id : int
  --
  name : varchar
}

entity "shows_genres" {
  + id : int
  --
  show_id : int
  genre_id : int
}

channels ||--o{ time_slots : has
shows ||--o{ seasons : has
seasons ||--o{ episodes : has
episodes ||--o{ view_counts : has
time_slots ||--o{ view_counts : has
shows ||--o{ shows_genres : has
genres ||--o{ shows_genres : has

@enduml
